name: CI
permissions:
  contents: read
  actions: read
  packages: read
  statuses: write
  checks: write
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (${{ matrix.unityVersion }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        unityVersion: [6000.0.49f1, 2023.2.20f1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      # Required when using package mode, see open issue:
      # https://github.com/game-ci/unity-test-runner/issues/223
      - name: Move Into Subdirectory
        shell: bash
        run: |
          mkdir root
          shopt -s dotglob extglob
          mv !(root) root/

      - name: Run Tests
        uses: game-ci/unity-test-runner@v4
        id: testRunner
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: root
          unityVersion: ${{ matrix.unityVersion }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Test Results (${{ matrix.unityVersion }})
          packageMode: true
          useHostNetwork: true
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test results (${{ matrix.unityVersion }})
          path: ${{ steps.testRunner.outputs.artifactsPath }}